server:
  port: "8080"    # Default port

database:
  host: "localhost"
  port: 5432
  name: "mydb_production"

jwt:
  publickey_path: "config/keys/public.pem"
  privatekey_path: "config/keys/private.pem"